#ifndef ENGINE_CLIENT_BACKEND_EMBEDDED_SHADERS_H
#define ENGINE_CLIENT_BACKEND_EMBEDDED_SHADERS_H

#include <cstddef>

// The shaders are part of the binary, not of the data directory: a client
// cannot start with a shader that does not match it, and nothing on disk can
// go missing. The table is generated by scripts/embed_shaders.py from the
// files in src/engine/client/backend/*/shaders; the GLSL sources are the text
// as written, the SPIR-V modules are what glslang made of them, four-byte
// aligned.
struct SEmbeddedShader
{
	const char *m_pName;
	const unsigned char *m_pData;
	size_t m_Size;
};

// Null when there is no shader of that name, which is a build error, not a
// runtime condition.
const SEmbeddedShader *FindEmbeddedShader(const char *pName);

#endif
