#ifndef ENGINE_CLIENT_BACKEND_EMBEDDED_SHADERS_H
#define ENGINE_CLIENT_BACKEND_EMBEDDED_SHADERS_H

#include <cstddef>

// Shaders embedded in the binary, generated by scripts/embed_shaders.py from
// src/engine/client/backend/shaders: GLSL as text, SPIR-V four-byte aligned.
struct SEmbeddedShader
{
	const char *m_pName;
	const unsigned char *m_pData;
	size_t m_Size;
};

// Null when there is no shader of that name, which is a build error, not a
// runtime condition.
const SEmbeddedShader *FindEmbeddedShader(const char *pName);

#endif
