#!/usr/bin/env python3
"""Turn shader files into a C++ table so that the binary carries them.

Usage: embed_shaders.py OUTPUT NAME=PATH [NAME=PATH ...]

Text files (GLSL) become string literals, binary files (SPIR-V) become
uint32 arrays. Both are reached through FindEmbeddedShader(NAME); see
src/engine/client/backend/embedded_shaders.h.
"""

import struct
import sys


def c_string_literal(text):
	out = []
	for line in text.split("\n"):
		escaped = line.replace("\\", "\\\\").replace('"', '\\"')
		out.append(f'\t"{escaped}\\n"')
	return "\n".join(out)


def main():
	if len(sys.argv) < 3:
		print(__doc__, file=sys.stderr)
		return 1
	output = sys.argv[1]
	entries = []
	for index, arg in enumerate(sys.argv[2:]):
		name, path = arg.split("=", 1)
		with open(path, "rb") as f:
			data = f.read()
		entries.append((name, path, data, index))

	parts = [
		"// Generated by scripts/embed_shaders.py. Do not edit.",
		"#include <engine/client/backend/embedded_shaders.h>",
		"",
		"#include <base/str.h>",
		"",
		"#include <cstdint>",
		"",
		"namespace {",
	]
	for name, path, data, index in entries:
		if name.endswith(".spv"):
			if len(data) % 4 != 0:
				print(f"{path}: SPIR-V size is not a multiple of four", file=sys.stderr)
				return 1
			words = struct.unpack(f"<{len(data) // 4}I", data)
			rows = []
			for start in range(0, len(words), 8):
				rows.append("\t" + ", ".join(f"0x{word:08x}" for word in words[start : start + 8]) + ",")
			parts.append(f"// {path}")
			parts.append(f"const uint32_t s_aShader{index}[] = {{")
			parts.extend(rows)
			parts.append("};")
		else:
			text = data.decode("utf-8").replace("\r\n", "\n")
			text = text.removesuffix("\n")
			parts.append(f"// {path}")
			parts.append(f"const char s_aShader{index}[] =")
			parts.append(c_string_literal(text) + ";")
		parts.append("")
	parts.append("const SEmbeddedShader s_aShaders[] = {")
	for name, path, data, index in entries:
		if name.endswith(".spv"):
			parts.append(f'\t{{"{name}", reinterpret_cast<const unsigned char *>(s_aShader{index}), sizeof(s_aShader{index})}},')
		else:
			parts.append(f'\t{{"{name}", reinterpret_cast<const unsigned char *>(s_aShader{index}), sizeof(s_aShader{index}) - 1}},')
	parts.append("};")
	parts.append("} // namespace")
	parts.append("")
	parts.append("const SEmbeddedShader *FindEmbeddedShader(const char *pName)")
	parts.append("{")
	parts.append("\tfor(const SEmbeddedShader &Shader : s_aShaders)")
	parts.append("\t{")
	parts.append("\t\tif(str_comp(Shader.m_pName, pName) == 0)")
	parts.append("\t\t\treturn &Shader;")
	parts.append("\t}")
	parts.append("\treturn nullptr;")
	parts.append("}")
	parts.append("")
	with open(output, "w", newline="\n") as f:
		f.write("\n".join(parts))
	return 0


if __name__ == "__main__":
	sys.exit(main())
